config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :ebooks do
    collection do
      post 'import'
      get 'choose'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'ebooks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ebook.rb
class Ebook < ApplicationRecord
  attr_accessor :book_local_path   ## Added extra special field for local filesystem import.
  has_attached_file :book
  validates_attachment :book,
                       :presence => true,
                       :content_type => { :content_type => /\A.*\Z/ },
                       :size => { :less_than => 128.megabytes }

  ## Everything below here is special code to deal with importing from the local filesystem ##
  
  before_validation :import_local_book, :if => :book_local_path_provided?

  validates_presence_of :book_local_path_, :if => :book_local_path_provided?, :message => 'is not accessible'

  private

  def book_local_path_provided?
    !self.book_local_path.blank?
  end

  def import_local_book
    self.book = do_import_local_book
    self.book_local_path_ = book_local_path
  end

  def do_import_local_book
    io = open(book_local_path)

    def io.original_filename; path.split('/').last; end

    io.original_filename.blank? ? nil : io

  rescue # Catch URL errors with validations, instead of exceptions.
    
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ebooks_controller.rb
class EbooksController < ApplicationController

  before_filter :authenticate_user!
  
  def index
    @ebooks = Ebook.order(:title).page(params[:page])
  end

  def new
    @ebook = Ebook.new
    @ebook.cover = "foo"
    @ebook.title = "foo"
    @ebook.titles = "foo"
    @ebook.languages = "foo"
    @ebook.contributors = "foo"
    @ebook.coverages = "foo"
    @ebook.creators = "foo"
    @ebook.dates = "foo"
    @ebook.descriptions = "foo"
    @ebook.formats = "foo"
    @ebook.publishers = "foo"
    @ebook.relations = "foo"
    @ebook.rights = "foo"
    @ebook.sources = "foo"
    @ebook.subjects = "foo"
    @ebook.types = "foo"
    @ebook.uniqueid = "foo"
    @ebook.epubver = "foo"
  end

  def create
    @ebook = Ebook.create(ebook_params)
    p = EPUB::Parser.parse(@ebook.book.path)
    @ebook.cover = "data:"+p.cover_image.media_type+"; base64," + Base64.encode64(p.cover_image.read) unless p.cover_image.nil?
    @ebook.title = p.title
    @ebook.titles = p.metadata.to_h[:titles][0].to_s unless p.metadata.to_h[:titles].nil?
    @ebook.languages = p.metadata.to_h[:languages][0].to_s unless p.metadata.to_h[:languages].nil?
    @ebook.contributors = p.metadata.to_h[:contributors][0].to_s unless p.metadata.to_h[:contributors].nil?
    @ebook.coverages = p.metadata.to_h[:coverages][0].to_s unless p.metadata.to_h[:coverages].nil?
    @ebook.creators = p.metadata.to_h[:creators][0].to_s unless p.metadata.to_h[:creators].nil?
    @ebook.dates = p.metadata.to_h[:dates][0].to_s unless p.metadata.to_h[:dates].nil?
    @ebook.descriptions = p.metadata.to_h[:descriptions][0].to_s unless p.metadata.to_h[:descriptions].nil?
    @ebook.formats = p.metadata.to_h[:formats][0].to_s unless p.metadata.to_h[:formats].nil?
    @ebook.publishers = p.metadata.to_h[:publishers][0].to_s unless p.metadata.to_h[:publishers].nil?
    @ebook.relations = p.metadata.to_h[:relations][0].to_s unless p.metadata.to_h[:relations].nil?
    @ebook.rights = p.metadata.to_h[:rights][0].to_s unless p.metadata.to_h[:rights].nil?
    @ebook.sources = p.metadata.to_h[:sources][0].to_s unless p.metadata.to_h[:sources].nil?
    @ebook.subjects = p.metadata.to_h[:subjects][0].to_s unless p.metadata.to_h[:subjects].nil?
    @ebook.types = p.metadata.to_h[:types][0].to_s unless p.metadata.to_h[:types].nil?
    @ebook.uniqueid = p.metadata.to_h[:uniqueid][0].to_s unless p.metadata.to_h[:uniqueid].nil?
    @ebook.epubver = p.metadata.to_h[:epubver][0].to_s unless p.metadata.to_h[:epubver].nil?

    if @ebook.save
      render json: { message: "success" }, :status => 200
    else
      render json: { error: @ebook.errors.full_messages.join(',')}, :status => 400
    end
  end

  def show
    @ebook = Ebook.find(params[:id])
    render :layout => "reader"
  end

  def destroy
    @ebook = Ebook.find(params[:id])
    @ebook.book.destroy
    @ebook.destroy
    redirect_to ebooks_url
  end

  def choose
  end
  
  def import
    @ebooks = []
    @path = params["path"]
    epubfiles = File.join(params["path"],"**","*.epub")
    Dir.glob(epubfiles).each do |file|
      ebook = Ebook.new(:book_local_path => file)
      p = EPUB::Parser.parse(file)
      ebook.cover = "data:"+p.cover_image.media_type+"; base64," + Base64.encode64(p.cover_image.read) unless p.cover_image.nil?
      ebook.title = p.title
      ebook.titles = p.metadata.to_h[:titles][0].to_s unless p.metadata.to_h[:titles].nil?
      ebook.languages = p.metadata.to_h[:languages][0].to_s unless p.metadata.to_h[:languages].nil?
      ebook.contributors = p.metadata.to_h[:contributors][0].to_s unless p.metadata.to_h[:contributors].nil?
      ebook.coverages = p.metadata.to_h[:coverages][0].to_s unless p.metadata.to_h[:coverages].nil?
      ebook.creators = p.metadata.to_h[:creators][0].to_s unless p.metadata.to_h[:creators].nil?
      ebook.dates = p.metadata.to_h[:dates][0].to_s unless p.metadata.to_h[:dates].nil?
      ebook.descriptions = p.metadata.to_h[:descriptions][0].to_s unless p.metadata.to_h[:descriptions].nil?
      ebook.formats = p.metadata.to_h[:formats][0].to_s unless p.metadata.to_h[:formats].nil?
      ebook.publishers = p.metadata.to_h[:publishers][0].to_s unless p.metadata.to_h[:publishers].nil?
      ebook.relations = p.metadata.to_h[:relations][0].to_s unless p.metadata.to_h[:relations].nil?
      ebook.rights = p.metadata.to_h[:rights][0].to_s unless p.metadata.to_h[:rights].nil?
      ebook.sources = p.metadata.to_h[:sources][0].to_s unless p.metadata.to_h[:sources].nil?
      ebook.subjects = p.metadata.to_h[:subjects][0].to_s unless p.metadata.to_h[:subjects].nil?
      ebook.types = p.metadata.to_h[:types][0].to_s unless p.metadata.to_h[:types].nil?
      ebook.uniqueid = p.metadata.to_h[:uniqueid][0].to_s unless p.metadata.to_h[:uniqueid].nil?
      ebook.epubver = p.metadata.to_h[:epubver][0].to_s unless p.metadata.to_h[:epubver].nil?

      if ebook.save
        @ebooks << ebook
      end

    end
    
  end
  
  private
  
  def ebook_params
    params.require(:ebook).permit(:title,:titles,:languages,:contributors,:coverages,:creators,:dates,:descriptions,:formats,:publishers,:relations,:rights,:sources,:subjects,:types,:uniqueid,:epubver,:book)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ebooks_helper.rb
module EbooksHelper

  def get_url(url)
    url[/^[^\?]*/]
  end

  def ebook_cover(cover)
    if cover.nil?
      image_path("ebook-icon.png")
    else
      cover
    end
  end
  
end

app/views/ebooks/_ebook.html.erb
<tr class="ebook" data-href="<%= ebook_url(ebook) %>">
  <td><img width="128" style="border: 2px solid #AAA; padding: 6px; border-radius: 12px;" src="<%= ebook_cover(ebook.cover) %>" alt="<%= ebook.id %>" /></td>
  <td><%= ebook.title %></td>
  <td><%= ebook.creators %></td>
</tr>

app/views/ebooks/_nobooks.html.erb
<div class="jumbotron">
  <center>
  <h1 class="display-3">Your Library is Empty</h1>
  <p class="lead">You can <%= link_to "upload some books.", new_ebook_path %> to fill up your library, or <%= link_to "choose from an existing local folder.", choose_ebooks_path %></p>
  <%= link_to "Upload Books", new_ebook_path, class: "btn btn-primary btn-lg" %> | 
  <%= link_to "Import From Local Filesystem", choose_ebooks_path, class: "btn btn-default btn-lg" %>
  </center>
</div>

app/views/ebooks/choose.html.erb
<div class="jumbotron">
  <center>
  <h1 class="display-3">Import from Filesystem</h1>
  <p class="lead">You can import books from your local filesystem, by entering a path in the field below. <br />The path you specify will be searched recursively for books ending in .epub, and automatically added to the library.</p>
  </center>
  
  <%= form_tag(import_ebooks_path, method: 'post') do %>
  <div class="form-group row">
    <%= label_tag 'path', "Local Filesystem Path", class: 'col-2 col-form-label' %>
    <div class="col-10">
      <%= text_field_tag 'path', nil, placeholder: 'Enter a location on your filesystem, such as: /tmp', class: 'form-control' %>
    </div>
  </div>
  <%= submit_tag "Import", class: "btn btn-primary" %>
  <% end %>
  
</div>

app/views/ebooks/import.html.erb
<div class="jumbotron">
  <center>
  <h1 class="display-3">Import Results</h1>
  <p class="lead">The following eBooks were found at the path <%= @path %> and were processed</p>
  </center>
</div>

<% if @ebooks.count < 1 %>
   <%= render "nobooks" %>
<% else %>
<table id="ebooks" data-toggle="table" data-search="true">
  <thead>
    <th data-field="Cover">Cover</th>
    <th data-field="Title" data-sortable="true">Title</th>
    <th data-field="Author(s)" data-sortable="true">Author(s)</th>
  </thead>
  <tbody class="page">
    <%= render @ebooks %>
  </tbody>
</table>
<% end %>

app/views/ebooks/index.html.erb
<% if @ebooks.count < 1 %>
   <%= render "nobooks" %>
<% else %>
<table id="ebooks" data-toggle="table" data-search="true">
  <thead>
    <th data-field="Cover">Cover</th>
    <th data-field="Title" data-sortable="true">Title</th>
    <th data-field="Author(s)" data-sortable="true">Author(s)</th>
  </thead>
  <tbody class="page">
    <%= render @ebooks %>
  </tbody>
</table>
<%= paginate @ebooks %>
<% end %>

app/views/ebooks/index.js.erb
$("#ebooks").append("<tbody class='page'><%= escape_javascript(render(@ebooks)) %></tbody>");

app/views/ebooks/new.html.erb
<%= form_for(@ebook, html: { multipart: true, class: "dropzone"}) do |f|  %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :titles %>
  <%= f.hidden_field :languages %>
  <%= f.hidden_field :contributors %>
  <%= f.hidden_field :coverages %>
  <%= f.hidden_field :creators %>
  <%= f.hidden_field :dates %>
  <%= f.hidden_field :descriptions %>
  <%= f.hidden_field :formats %>
  <%= f.hidden_field :publishers %>
  <%= f.hidden_field :relations %>
  <%= f.hidden_field :rights %>
  <%= f.hidden_field :sources %>
  <%= f.hidden_field :subjects %>
  <%= f.hidden_field :types %>
  <%= f.hidden_field :uniqueid %>
  <%= f.hidden_field :epubver %>

<div class="fallback">
  <%= f.file_field :book %><br>
  <%= f.submit "Upload" %>
</div>
<% end %>

app/views/ebooks/show.html.erb
      <div id="sidebar">
        <div id="panels">
          <input id="searchBox" placeholder="search" type="search">

          <a id="show-Search" class="show_view icon-search" data-view="Search">Search</a>
          <a id="show-Toc" class="show_view icon-list-1 active" data-view="Toc">TOC</a>
          <a id="show-Bookmarks" class="show_view icon-bookmark" data-view="Bookmarks">Bookmarks</a>
          <a id="show-Notes" class="show_view icon-edit" data-view="Notes">Notes</a>

        </div>
        <div id="tocView" class="view">
        </div>
        <div id="searchView" class="view">
          <ul id="searchResults"></ul>
        </div>
        <div id="bookmarksView" class="view">
          <ul id="bookmarks"></ul>
        </div>
        <div id="notesView" class="view">
          <div id="new-note">
            <textarea id="note-text"></textarea>
            <button id="note-anchor">Anchor</button>
          </div>
          <ol id="notes"></ol>
        </div>
      </div>
      <div id="main">

        <div id="titlebar">
          <div id="opener">
            <a id="slider" class="icon-menu">Menu</a>
          </div>
          <div id="metainfo">
            <span id="book-title"></span>
            <span id="title-seperator">&nbsp;&nbsp;–&nbsp;&nbsp;</span>
            <span id="chapter-title"></span>
          </div>
          <div id="title-controls">
            <a id="bookmark" class="icon-bookmark-empty">Bookmark</a>
            <a id="fullscreen" class="icon-resize-full">Fullscreen</a>
	    <%= link_to "Delete", url_for(action: :destroy, id: @ebook.id), method: :delete, class: "eicon-trash", data: {confirm: "Are you sure?"} %>
	    <a id="close" href="<%= ebooks_path %>" class="icon-cancel-circled">Close</a>
          </div>
        </div>

        <div id="divider"></div>
        <div id="prev" class="arrow">‹</div>
        <div id="viewer"></div>
        <div id="next" class="arrow">›</div>

        <div id="loader"><img src="<%= image_path('loader.gif') %>"></div>
      </div>
      <div class="overlay"></div>

        <script>
          "use strict";
	  
          document.onreadystatechange = function () {
            if (document.readyState == "complete") {
              EPUBJS.filePath = "js/libs/";
              EPUBJS.cssPath = "/css/";
              window.reader = ePubReader("<%= get_url(@ebook.book.url) %>");
              $("div#main").hammer().bind("swipeleft", function(ev) { window.reader.book.nextPage(); }).bind("swiperight",function(ev) { window.reader.book.prevPage(); });
	  
            }
          };
	  
        </script>

app/views/layouts/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	<span class="sr-only">Toggle navigation</span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </button>
      <%= link_to "reading:CLOUD", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
	<li class="<%= 'active' if (current_page?(root_path) || current_page?(ebooks_path)) %>"><%= link_to "Books", root_path, class: "nav-link" %></li>
	<li class="<%= 'active' if current_page?(new_ebook_path) %>"><%= link_to "Upload", new_ebook_path, :class => "nav_link" %></li>
	<li class="<%= 'active' if current_page?(choose_ebooks_path) %>"><%= link_to "Import", choose_ebooks_path, :class => "nav_link" %></li>
	<li><%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "nav_link") %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Readingcloud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/reader.html.erb
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, user-scalable=no">
        <meta name="apple-mobile-web-app-capable" content="yes">

	<%= csrf_meta_tags %>
	
	<%= stylesheet_link_tag    'ebook-reader', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'ebook-reader', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
      <%= yield %>
    </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>